/**
 * Synthetic data narratives — the single generator behind BOTH synthetic databases:
 *
 * - `demo`  — rich 8-year life story for the hosted recruiter demo (multi-card, cuotas,
 *             USD statements, property purchase).
 * - `test`  — lean deterministic dataset for Vitest (short window, one card, small
 *             merchant pool) generated by `vitest.globalSetup` so the suite never copies
 *             personal data.
 *
 * All money flows originate from one checking account plus the configured credit cards —
 * the same "master moves" model the reconciliation engine expects — so every derived
 * surface (deposits matching, billing months, gastos categories, net-worth buckets) is
 * internally consistent by construction.
 *
 * Both presets end at the CURRENT calendar month so current-month/rollover code paths
 * always have data; the seed keeps the history deterministic for a given month.
 */
import { monthKeyFromYmd } from "../calendarMonth.js";
import { chileCalendarTodayYmd } from "../chileDate.js";

/** `YYYY-MM`. */
export type DemoMonth = string;

export type DemoPreset = "demo" | "test";

export type DemoChapterId =
  | "first_job_at_parents"
  | "first_apartment"
  | "pandemic_lockdown"
  | "back_with_parents"
  | "renting_again"
  | "own_house"
  | "test_baseline";

/** A recurring checking bill (rent, luz, internet, dividendo, …) with its gastos category. */
export type DemoBill = {
  /** Cartola description — also the merchant key the seeded category rule matches on. */
  desc: string;
  meanClp: number;
  /** `cc_expense_categories` slug (bills / others / real_estate_amortization / …). */
  categorySlug: string;
  day: number;
  /** Bill fires on calendar months divisible by this (contribuciones = 3). Default 1. */
  everyNMonths?: number;
};

export type DemoChapter = {
  id: DemoChapterId;
  /** Inclusive start month. Chapter runs until the next chapter's start. */
  from: DemoMonth;
  /** Net monthly salary landing in checking (CLP). Grows by `salaryAnnualGrowth`. */
  salaryClp: number;
  salaryAnnualGrowth: number;
  /** Itemized fixed outflows from checking — one movement per bill, categorized. */
  bills: DemoBill[];
  /** Mean discretionary CC spend per month across all cards. */
  ccSpendMeanClp: number;
  /** Weight multipliers per gastos category for this chapter (supermarket, fun, …). */
  categoryWeights?: Record<string, number>;
};

export type DemoEventKind =
  | "moving_costs"
  | "vacation_small"
  | "vacation_medium"
  | "vacation_big"
  | "house_down_payment"
  | "bonus";

export type DemoEvent = {
  month: DemoMonth;
  kind: DemoEventKind;
  /** Positive = extra spend (CC unless `viaChecking`), negative = extra income. */
  amountClp: number;
  viaChecking?: boolean;
  /** Big purchases can bill as N cuotas on the card (exercises installment views). */
  cuotas?: number;
  label: string;
  /** last4 of the card the event bills on (defaults to the first active card). */
  cardLast4?: string;
};

/** Scripted portfolio moves — buys are CLP from checking, sells a fraction of holdings. */
export type DemoTrade = {
  month: DemoMonth;
  asset: "stocks" | "crypto" | "fondo";
  action: "buy" | "sell";
  /** CLP amount for buys. */
  amountClp?: number;
  /** Fraction of current value for sells (0–1). */
  fraction?: number;
  /** Stock trades target one ticker (defaults to the first configured position). */
  ticker?: string;
};

export type DemoCard = {
  last4: string;
  cardGroup: "santander" | "bci";
  displayName: string;
  /** First month the card exists (statements start here). */
  from: DemoMonth;
  /** Relative share of the chapter's discretionary spend once active. */
  spendShare: number;
  /** Extra category weight multipliers stacked on the chapter's (per-card flavor). */
  merchantBias?: Record<string, number>;
  /** Monthly international USD purchases (adds a USD statement per month). */
  usdMonthly?: { meanUsd: number };
};

export type DemoNarrative = {
  preset: DemoPreset;
  /** Deterministic PRNG seed — same seed + same month, same DB. */
  seed: number;
  firstMonth: DemoMonth;
  /** Always the current calendar month — the demo/test data never goes stale. */
  lastMonth: DemoMonth;
  chapters: DemoChapter[];
  events: DemoEvent[];
  cards: DemoCard[];
  /** Investment accounts to create (fondo always; AFP/property optional). */
  withAfp: boolean;
  withProperty: boolean;
  /**
   * Stock portfolio: monthly buys redirect a share of the sweep from `from` on, split
   * across positions by weight. Tickers must have `brokerage_acciones__<ticker>` leaves
   * and synthetic `equity_daily` price anchors in the writers.
   */
  stocks: {
    from: DemoMonth;
    sweepShare: number;
    positions: { ticker: string; weight: number }[];
  } | null;
  /** Crypto position (created only when `trades` buys into it). */
  withCrypto: boolean;
  /** Scripted buys/sells (rescates, take-profits, capitulations) for the "life" in the chart. */
  trades: DemoTrade[];
  /**
   * Leveraged house purchase: full property value + amortizing mortgage liability from
   * `month` on (down payment stays a separate viaChecking event). Without this, presets
   * with `withProperty` fall back to the bare down-payment valuation.
   */
  house: {
    month: DemoMonth;
    valueClp: number;
    mortgageClp: number;
    termMonths: number;
    monthlyRate: number;
  } | null;
};

function currentMonth(): DemoMonth {
  return monthKeyFromYmd(chileCalendarTodayYmd());
}

function monthsBack(n: number): DemoMonth {
  const cur = currentMonth();
  let y = Number(cur.slice(0, 4));
  let m = Number(cur.slice(5, 7)) - n;
  while (m <= 0) {
    m += 12;
    y -= 1;
  }
  return `${y}-${String(m).padStart(2, "0")}`;
}

/**
 * Rich recruiter-demo narrative: start working while living with parents → first
 * apartment → May-2020 lockdown dip → big trip then back with parents → renting again →
 * house purchase, with vacations of varying size throughout — three cards, one with a
 * monthly USD stream.
 */
function demoNarrative(): DemoNarrative {
  return {
    preset: "demo",
    seed: 20260701,
    firstMonth: "2018-03",
    lastMonth: currentMonth(),
    chapters: [
      {
        id: "first_job_at_parents",
        from: "2018-03",
        salaryClp: 900_000,
        salaryAnnualGrowth: 0.08,
        bills: [
          { desc: "APORTE GASTOS CASA FAMILIAR", meanClp: 45_000, categorySlug: "others", day: 5 },
          { desc: "PLAN CELULAR ENTEL", meanClp: 20_000, categorySlug: "bills", day: 10 },
          { desc: "GIMNASIO POWER FIT", meanClp: 15_000, categorySlug: "fun", day: 6 },
        ],
        ccSpendMeanClp: 150_000,
        categoryWeights: { fun: 1.4, supermarket: 0.3 },
      },
      {
        id: "first_apartment",
        from: "2019-06",
        salaryClp: 1_250_000,
        salaryAnnualGrowth: 0.07,
        bills: [
          { desc: "PAGO ARRIENDO DEPTO PROVIDENCIA", meanClp: 500_000, categorySlug: "others", day: 5 },
          { desc: "GASTOS COMUNES EDIFICIO", meanClp: 55_000, categorySlug: "bills", day: 6 },
          { desc: "ENEL CHILE", meanClp: 28_000, categorySlug: "bills", day: 12 },
          { desc: "AGUAS ANDINAS", meanClp: 14_000, categorySlug: "bills", day: 12 },
          { desc: "VTR INTERNET", meanClp: 26_000, categorySlug: "bills", day: 15 },
          { desc: "PLAN CELULAR ENTEL", meanClp: 22_000, categorySlug: "bills", day: 10 },
          { desc: "GIMNASIO POWER FIT", meanClp: 25_000, categorySlug: "fun", day: 6 },
        ],
        ccSpendMeanClp: 320_000,
        categoryWeights: { supermarket: 1.3, bills: 1.2 },
      },
      {
        id: "pandemic_lockdown",
        from: "2020-04",
        salaryClp: 1_320_000,
        salaryAnnualGrowth: 0.05,
        bills: [
          { desc: "PAGO ARRIENDO DEPTO PROVIDENCIA", meanClp: 500_000, categorySlug: "others", day: 5 },
          { desc: "GASTOS COMUNES EDIFICIO", meanClp: 55_000, categorySlug: "bills", day: 6 },
          { desc: "ENEL CHILE", meanClp: 36_000, categorySlug: "bills", day: 12 },
          { desc: "AGUAS ANDINAS", meanClp: 16_000, categorySlug: "bills", day: 12 },
          { desc: "VTR INTERNET", meanClp: 32_000, categorySlug: "bills", day: 15 },
          { desc: "PLAN CELULAR ENTEL", meanClp: 22_000, categorySlug: "bills", day: 10 },
        ],
        ccSpendMeanClp: 140_000,
        categoryWeights: { fun: 0.2, supermarket: 1.5, delivery: 1.6 },
      },
      {
        id: "back_with_parents",
        from: "2021-09",
        salaryClp: 1_650_000,
        salaryAnnualGrowth: 0.08,
        bills: [
          { desc: "APORTE GASTOS CASA FAMILIAR", meanClp: 60_000, categorySlug: "others", day: 5 },
          { desc: "PLAN CELULAR ENTEL", meanClp: 25_000, categorySlug: "bills", day: 10 },
          { desc: "BODEGA STORAGE CENTRO", meanClp: 35_000, categorySlug: "others", day: 8 },
        ],
        ccSpendMeanClp: 260_000,
      },
      {
        id: "renting_again",
        from: "2022-11",
        salaryClp: 3_200_000,
        salaryAnnualGrowth: 0.07,
        bills: [
          { desc: "PAGO ARRIENDO DEPTO LAS CONDES", meanClp: 700_000, categorySlug: "others", day: 5 },
          { desc: "GASTOS COMUNES EDIFICIO", meanClp: 85_000, categorySlug: "bills", day: 6 },
          { desc: "ENEL CHILE", meanClp: 35_000, categorySlug: "bills", day: 12 },
          { desc: "AGUAS ANDINAS", meanClp: 17_000, categorySlug: "bills", day: 12 },
          { desc: "VTR INTERNET", meanClp: 28_000, categorySlug: "bills", day: 15 },
          { desc: "PLAN CELULAR ENTEL", meanClp: 25_000, categorySlug: "bills", day: 10 },
          { desc: "GIMNASIO POWER FIT", meanClp: 20_000, categorySlug: "fun", day: 6 },
        ],
        ccSpendMeanClp: 420_000,
      },
      {
        id: "own_house",
        from: "2024-08",
        salaryClp: 5_200_000,
        salaryAnnualGrowth: 0.06,
        bills: [
          // The dividendo is NOT a checking bill: it bills on the main credit card (like
          // the real DB's PAT) so the mortgage expense-deposit link machinery splits it
          // into carrying cost + amortization. See writeCreditCardMonth.
          { desc: "CONTRIBUCIONES TESORERIA", meanClp: 900_000, categorySlug: "bills", day: 28, everyNMonths: 3 },
          { desc: "ENEL CHILE", meanClp: 60_000, categorySlug: "bills", day: 12 },
          { desc: "AGUAS ANDINAS", meanClp: 30_000, categorySlug: "bills", day: 12 },
          { desc: "METROGAS", meanClp: 45_000, categorySlug: "bills", day: 14 },
          { desc: "VTR INTERNET", meanClp: 32_000, categorySlug: "bills", day: 15 },
          { desc: "PLAN CELULAR ENTEL", meanClp: 30_000, categorySlug: "bills", day: 10 },
          { desc: "SEGURO HOGAR DEMO", meanClp: 35_000, categorySlug: "bills", day: 20 },
          { desc: "JARDINERO DON PEDRO", meanClp: 45_000, categorySlug: "trees", day: 22, everyNMonths: 2 },
          { desc: "MANTENCION CASA VARIOS", meanClp: 60_000, categorySlug: "others", day: 18 },
          { desc: "GIMNASIO POWER FIT", meanClp: 25_000, categorySlug: "fun", day: 6 },
        ],
        ccSpendMeanClp: 480_000,
        categoryWeights: { home: 1.5 },
      },
    ],
    events: [
      { month: "2019-06", kind: "moving_costs", amountClp: 450_000, cuotas: 3, label: "Mudanza depto" },
      { month: "2019-09", kind: "bonus", amountClp: -800_000, viaChecking: true, label: "Bono fiestas patrias" },
      { month: "2019-12", kind: "vacation_small", amountClp: 380_000, label: "Vacaciones sur" },
      { month: "2021-07", kind: "vacation_big", amountClp: 2_400_000, cuotas: 6, label: "Gran viaje" },
      { month: "2020-12", kind: "bonus", amountClp: -1_200_000, viaChecking: true, label: "Bono desempeño" },
      { month: "2022-02", kind: "vacation_small", amountClp: 420_000, label: "Playa" },
      { month: "2022-12", kind: "bonus", amountClp: -1_500_000, viaChecking: true, label: "Bono desempeño" },
      { month: "2022-11", kind: "moving_costs", amountClp: 380_000, label: "Mudanza arriendo" },
      { month: "2023-07", kind: "vacation_medium", amountClp: 1_100_000, cuotas: 3, label: "Viaje", cardLast4: "8912" },
      { month: "2024-01", kind: "vacation_medium", amountClp: 900_000, label: "Verano" },
      { month: "2024-08", kind: "house_down_payment", amountClp: 100_000_000, viaChecking: true, label: "Pie casa" },
      { month: "2024-08", kind: "moving_costs", amountClp: 600_000, cuotas: 6, label: "Mudanza casa" },
      { month: "2023-09", kind: "moving_costs", amountClp: 480_000, cuotas: 6, label: "Smart TV", cardLast4: "6605" },
      { month: "2024-04", kind: "moving_costs", amountClp: 360_000, cuotas: 3, label: "Refrigerador", cardLast4: "6605" },
      { month: "2024-12", kind: "bonus", amountClp: -1_800_000, viaChecking: true, label: "Bono desempeño" },
      { month: "2025-12", kind: "moving_costs", amountClp: 700_000, cuotas: 6, label: "Notebook", cardLast4: "6605" },
      { month: "2026-04", kind: "moving_costs", amountClp: 240_000, cuotas: 3, label: "Terraza", cardLast4: "6605" },
      // Keeps the BCI card carrying an open cuota balance "today" (facturado + próximo pago
      // non-zero on the demo) — otherwise every ledger purchase is fully paid by mid-2026.
      { month: "2026-06", kind: "moving_costs", amountClp: 540_000, cuotas: 6, label: "Bicicleta", cardLast4: "6605" },
      { month: "2025-02", kind: "vacation_small", amountClp: 450_000, label: "Playa" },
      { month: "2025-03", kind: "moving_costs", amountClp: 840_000, cuotas: 12, label: "Arreglos casa", cardLast4: "6605" },
      { month: "2025-09", kind: "vacation_big", amountClp: 2_100_000, cuotas: 6, label: "Viaje largo", cardLast4: "8912" },
      { month: "2026-01", kind: "vacation_medium", amountClp: 950_000, label: "Verano" },
    ],
    cards: [
      {
        last4: "4321",
        cardGroup: "santander",
        displayName: "Tarjeta Santander 4321",
        from: "2018-03",
        spendShare: 1,
      },
      {
        last4: "8912",
        cardGroup: "santander",
        displayName: "Tarjeta Santander 8912",
        from: "2022-11",
        spendShare: 0.6,
        merchantBias: { fun: 1.5, transport: 1.4 },
        usdMonthly: { meanUsd: 120 },
      },
      {
        last4: "6605",
        cardGroup: "bci",
        displayName: "Tarjeta BCI 6605",
        from: "2023-06",
        spendShare: 0.35,
        merchantBias: { supermarket: 2.0, home: 1.5 },
      },
    ],
    withAfp: true,
    withProperty: true,
    stocks: {
      from: "2019-01",
      sweepShare: 0.4,
      positions: [
        { ticker: "NVDA", weight: 0.4 },
        { ticker: "SPY", weight: 0.2 },
        { ticker: "SMH", weight: 0.25 },
        { ticker: "CCJ", weight: 0.15 },
        // Weight 0: no sweep allocation — INTC exists only for the scripted 2024
        // turnaround bet that implodes (bought ~$44, exited ~$20).
        { ticker: "INTC", weight: 0 },
      ],
    },
    withCrypto: true,
    trades: [
      { month: "2020-10", asset: "crypto", action: "buy", amountClp: 500_000 },
      { month: "2020-12", asset: "crypto", action: "buy", amountClp: 500_000 },
      { month: "2021-02", asset: "crypto", action: "buy", amountClp: 1_000_000 },
      // Early NVDA conviction, doubled down on the COVID dip; semis ETF rides along.
      { month: "2019-10", asset: "stocks", action: "buy", amountClp: 1_000_000, ticker: "NVDA" },
      { month: "2020-04", asset: "stocks", action: "buy", amountClp: 1_500_000, ticker: "NVDA" },
      { month: "2020-05", asset: "stocks", action: "buy", amountClp: 2_000_000, ticker: "SMH" },
      { month: "2021-03", asset: "stocks", action: "buy", amountClp: 1_500_000, ticker: "SMH" },
      // Nov-2021 top: take profit on both before the 2022 grind down.
      { month: "2021-11", asset: "crypto", action: "sell", fraction: 0.4 },
      { month: "2021-11", asset: "stocks", action: "sell", fraction: 0.3, ticker: "CCJ" },
      // Oct-2022 rotation: capitulate on the index, buy the AI-winter NVDA dip.
      { month: "2022-10", asset: "stocks", action: "sell", fraction: 0.15, ticker: "SPY" },
      { month: "2022-10", asset: "stocks", action: "buy", amountClp: 2_000_000, ticker: "NVDA" },
      { month: "2023-02", asset: "crypto", action: "buy", amountClp: 800_000 },
      // Feb-2024: the Intel foundry-turnaround bet — promising on paper, imploding by
      // August (the same week as the house purchase), exited in December at a ~55% loss.
      { month: "2024-02", asset: "stocks", action: "buy", amountClp: 4_000_000, ticker: "INTC" },
      // House funding: rebalance the big winners — sell most of NVDA and SMH + rescate
      // fondo the month before the pie (the 100M down payment comes from the portfolio,
      // keeping ~20M invested across the survivors).
      { month: "2024-07", asset: "stocks", action: "sell", fraction: 0.9, ticker: "NVDA" },
      { month: "2024-07", asset: "stocks", action: "sell", fraction: 0.75, ticker: "SMH" },
      { month: "2024-07", asset: "fondo", action: "sell", fraction: 0.35 },
      { month: "2024-12", asset: "stocks", action: "sell", fraction: 1, ticker: "INTC" },
      { month: "2025-01", asset: "stocks", action: "buy", amountClp: 2_000_000, ticker: "CCJ" },
    ],
    house: {
      month: "2024-08",
      valueClp: 500_000_000,
      mortgageClp: 400_000_000,
      termMonths: 300,
      monthlyRate: 0.00375,
    },
  };
}

/**
 * Lean Vitest narrative: ~18 months, one card, one cuota purchase (so installment-ledger
 * paths have rows), AFP + fondo for bucket coverage, no property. Deterministic for a
 * given calendar month.
 */
function testNarrative(): DemoNarrative {
  const first = monthsBack(17);
  return {
    preset: "test",
    seed: 424242,
    firstMonth: first,
    lastMonth: currentMonth(),
    chapters: [
      {
        id: "test_baseline",
        from: first,
        salaryClp: 1_500_000,
        salaryAnnualGrowth: 0.05,
        bills: [
          { desc: "PAGO ARRIENDO DEPTO TEST", meanClp: 320_000, categorySlug: "others", day: 5 },
          { desc: "ENEL CHILE", meanClp: 40_000, categorySlug: "bills", day: 12 },
          { desc: "VTR INTERNET", meanClp: 30_000, categorySlug: "bills", day: 15 },
          { desc: "PLAN CELULAR ENTEL", meanClp: 25_000, categorySlug: "bills", day: 10 },
        ],
        ccSpendMeanClp: 300_000,
      },
    ],
    events: [
      { month: monthsBack(9), kind: "vacation_medium", amountClp: 600_000, cuotas: 6, label: "Viaje test" },
      { month: monthsBack(3), kind: "vacation_small", amountClp: 200_000, label: "Escapada test" },
    ],
    cards: [
      {
        last4: "4321",
        cardGroup: "santander",
        displayName: "Tarjeta · Test Bank 4321",
        from: first,
        spendShare: 1,
        usdMonthly: { meanUsd: 80 },
      },
      {
        last4: "6605",
        cardGroup: "bci",
        displayName: "Tarjeta · Test Retail 6605",
        from: monthsBack(11),
        spendShare: 0.4,
      },
    ],
    withAfp: true,
    withProperty: false,
    stocks: null,
    withCrypto: false,
    trades: [],
    house: null,
  };
}

export function demoNarrativeForPreset(preset: DemoPreset): DemoNarrative {
  return preset === "test" ? testNarrative() : demoNarrative();
}

/** Chapter in effect for a month (chapters sorted by `from`; last one whose from ≤ month). */
export function chapterForMonth(narrative: DemoNarrative, month: DemoMonth): DemoChapter {
  const sorted = [...narrative.chapters].sort((a, b) => a.from.localeCompare(b.from));
  let current = sorted[0];
  if (!current) throw new Error("demo narrative needs at least one chapter");
  for (const ch of sorted) {
    if (ch.from <= month) current = ch;
  }
  return current;
}

/** Deterministic mulberry32 PRNG — same narrative seed ⇒ identical DB. */
export function demoRng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
