/**
 * Synthetic data narratives — the single generator behind BOTH synthetic databases:
 *
 * - `demo`  — rich 8-year life story for the hosted recruiter demo (multi-card, cuotas,
 *             USD statements, property purchase).
 * - `test`  — lean deterministic dataset for Vitest (short window, one card, small
 *             merchant pool) generated by `vitest.globalSetup` so the suite never copies
 *             personal data.
 *
 * All money flows originate from one checking account plus the configured credit cards —
 * the same "master moves" model the reconciliation engine expects — so every derived
 * surface (deposits matching, billing months, gastos categories, net-worth buckets) is
 * internally consistent by construction.
 *
 * Both presets end at the CURRENT calendar month so current-month/rollover code paths
 * always have data; the seed keeps the history deterministic for a given month.
 */
import { monthKeyFromYmd } from "../calendarMonth.js";
import { chileCalendarTodayYmd } from "../chileDate.js";

/** `YYYY-MM`. */
export type DemoMonth = string;

export type DemoPreset = "demo" | "test";

export type DemoChapterId =
  | "first_job_at_parents"
  | "first_apartment"
  | "pandemic_lockdown"
  | "back_with_parents"
  | "renting_again"
  | "own_house"
  | "test_baseline";

export type DemoChapter = {
  id: DemoChapterId;
  /** Inclusive start month. Chapter runs until the next chapter's start. */
  from: DemoMonth;
  /** Net monthly salary landing in checking (CLP). Grows by `salaryAnnualGrowth`. */
  salaryClp: number;
  salaryAnnualGrowth: number;
  /** Fixed monthly outflows from checking (rent/mortgage, bills, fees). */
  fixedExpensesClp: number;
  /** Mean discretionary CC spend per month across all cards. */
  ccSpendMeanClp: number;
  /** Fraction of leftover cash swept to investments/savings each month (0–1). */
  savingsRate: number;
  /** Weight multipliers per gastos category for this chapter (supermarket, fun, …). */
  categoryWeights?: Record<string, number>;
};

export type DemoEventKind =
  | "moving_costs"
  | "vacation_small"
  | "vacation_medium"
  | "vacation_big"
  | "house_down_payment"
  | "bonus";

export type DemoEvent = {
  month: DemoMonth;
  kind: DemoEventKind;
  /** Positive = extra spend (CC unless `viaChecking`), negative = extra income. */
  amountClp: number;
  viaChecking?: boolean;
  /** Big purchases can bill as N cuotas on the card (exercises installment views). */
  cuotas?: number;
  label: string;
  /** last4 of the card the event bills on (defaults to the first active card). */
  cardLast4?: string;
};

export type DemoCard = {
  last4: string;
  cardGroup: "santander" | "bci";
  displayName: string;
  /** First month the card exists (statements start here). */
  from: DemoMonth;
  /** Relative share of the chapter's discretionary spend once active. */
  spendShare: number;
  /** Extra category weight multipliers stacked on the chapter's (per-card flavor). */
  merchantBias?: Record<string, number>;
  /** Monthly international USD purchases (adds a USD statement per month). */
  usdMonthly?: { meanUsd: number };
};

export type DemoNarrative = {
  preset: DemoPreset;
  /** Deterministic PRNG seed — same seed + same month, same DB. */
  seed: number;
  firstMonth: DemoMonth;
  /** Always the current calendar month — the demo/test data never goes stale. */
  lastMonth: DemoMonth;
  chapters: DemoChapter[];
  events: DemoEvent[];
  cards: DemoCard[];
  /** Investment accounts to create (fondo always; AFP/property optional). */
  withAfp: boolean;
  withProperty: boolean;
};

function currentMonth(): DemoMonth {
  return monthKeyFromYmd(chileCalendarTodayYmd());
}

function monthsBack(n: number): DemoMonth {
  const cur = currentMonth();
  let y = Number(cur.slice(0, 4));
  let m = Number(cur.slice(5, 7)) - n;
  while (m <= 0) {
    m += 12;
    y -= 1;
  }
  return `${y}-${String(m).padStart(2, "0")}`;
}

/**
 * Rich recruiter-demo narrative: start working while living with parents → first
 * apartment → May-2020 lockdown dip → big trip then back with parents → renting again →
 * house purchase, with vacations of varying size throughout — three cards, one with a
 * monthly USD stream.
 */
function demoNarrative(): DemoNarrative {
  return {
    preset: "demo",
    seed: 20260701,
    firstMonth: "2018-03",
    lastMonth: currentMonth(),
    chapters: [
      {
        id: "first_job_at_parents",
        from: "2018-03",
        salaryClp: 900_000,
        salaryAnnualGrowth: 0.08,
        fixedExpensesClp: 80_000,
        ccSpendMeanClp: 150_000,
        savingsRate: 0.55,
        categoryWeights: { fun: 1.4, supermarket: 0.3 },
      },
      {
        id: "first_apartment",
        from: "2019-06",
        salaryClp: 1_250_000,
        salaryAnnualGrowth: 0.07,
        fixedExpensesClp: 520_000,
        ccSpendMeanClp: 320_000,
        savingsRate: 0.2,
        categoryWeights: { supermarket: 1.3, bills: 1.2 },
      },
      {
        id: "pandemic_lockdown",
        from: "2020-04",
        salaryClp: 1_320_000,
        salaryAnnualGrowth: 0.05,
        fixedExpensesClp: 520_000,
        ccSpendMeanClp: 140_000,
        savingsRate: 0.45,
        categoryWeights: { fun: 0.2, supermarket: 1.5, delivery: 1.6 },
      },
      {
        id: "back_with_parents",
        from: "2021-09",
        salaryClp: 1_650_000,
        salaryAnnualGrowth: 0.08,
        fixedExpensesClp: 120_000,
        ccSpendMeanClp: 260_000,
        savingsRate: 0.55,
      },
      {
        id: "renting_again",
        from: "2022-11",
        salaryClp: 2_100_000,
        salaryAnnualGrowth: 0.07,
        fixedExpensesClp: 680_000,
        ccSpendMeanClp: 420_000,
        savingsRate: 0.3,
      },
      {
        id: "own_house",
        from: "2024-08",
        salaryClp: 2_600_000,
        salaryAnnualGrowth: 0.06,
        fixedExpensesClp: 950_000,
        ccSpendMeanClp: 480_000,
        savingsRate: 0.25,
        categoryWeights: { home: 1.5 },
      },
    ],
    events: [
      { month: "2019-06", kind: "moving_costs", amountClp: 450_000, cuotas: 3, label: "Mudanza depto" },
      { month: "2019-12", kind: "vacation_small", amountClp: 380_000, label: "Vacaciones sur" },
      { month: "2021-07", kind: "vacation_big", amountClp: 2_400_000, cuotas: 6, label: "Gran viaje" },
      { month: "2022-02", kind: "vacation_small", amountClp: 420_000, label: "Playa" },
      { month: "2022-11", kind: "moving_costs", amountClp: 380_000, label: "Mudanza arriendo" },
      { month: "2023-07", kind: "vacation_medium", amountClp: 1_100_000, cuotas: 3, label: "Viaje", cardLast4: "8912" },
      { month: "2024-01", kind: "vacation_medium", amountClp: 900_000, label: "Verano" },
      { month: "2024-08", kind: "house_down_payment", amountClp: 18_000_000, viaChecking: true, label: "Pie casa" },
      { month: "2024-08", kind: "moving_costs", amountClp: 600_000, cuotas: 6, label: "Mudanza casa" },
      { month: "2025-02", kind: "vacation_small", amountClp: 450_000, label: "Playa" },
      { month: "2025-09", kind: "vacation_big", amountClp: 2_100_000, cuotas: 6, label: "Viaje largo", cardLast4: "8912" },
      { month: "2026-01", kind: "vacation_medium", amountClp: 950_000, label: "Verano" },
    ],
    cards: [
      {
        last4: "4321",
        cardGroup: "santander",
        displayName: "Tarjeta · Demo Bank 4321",
        from: "2018-03",
        spendShare: 1,
      },
      {
        last4: "8912",
        cardGroup: "santander",
        displayName: "Tarjeta · Demo Bank 8912",
        from: "2022-11",
        spendShare: 0.6,
        merchantBias: { fun: 1.5, transport: 1.4 },
        usdMonthly: { meanUsd: 120 },
      },
      {
        last4: "6605",
        cardGroup: "bci",
        displayName: "Tarjeta · Demo Retail 6605",
        from: "2023-06",
        spendShare: 0.35,
        merchantBias: { supermarket: 2.0, home: 1.5 },
      },
    ],
    withAfp: true,
    withProperty: true,
  };
}

/**
 * Lean Vitest narrative: ~18 months, one card, one cuota purchase (so installment-ledger
 * paths have rows), AFP + fondo for bucket coverage, no property. Deterministic for a
 * given calendar month.
 */
function testNarrative(): DemoNarrative {
  const first = monthsBack(17);
  return {
    preset: "test",
    seed: 424242,
    firstMonth: first,
    lastMonth: currentMonth(),
    chapters: [
      {
        id: "test_baseline",
        from: first,
        salaryClp: 1_500_000,
        salaryAnnualGrowth: 0.05,
        fixedExpensesClp: 450_000,
        ccSpendMeanClp: 300_000,
        savingsRate: 0.35,
      },
    ],
    events: [
      { month: monthsBack(9), kind: "vacation_medium", amountClp: 600_000, cuotas: 6, label: "Viaje test" },
      { month: monthsBack(3), kind: "vacation_small", amountClp: 200_000, label: "Escapada test" },
    ],
    cards: [
      {
        last4: "4321",
        cardGroup: "santander",
        displayName: "Tarjeta · Test Bank 4321",
        from: first,
        spendShare: 1,
        usdMonthly: { meanUsd: 80 },
      },
      {
        last4: "6605",
        cardGroup: "bci",
        displayName: "Tarjeta · Test Retail 6605",
        from: monthsBack(11),
        spendShare: 0.4,
      },
    ],
    withAfp: true,
    withProperty: false,
  };
}

export function demoNarrativeForPreset(preset: DemoPreset): DemoNarrative {
  return preset === "test" ? testNarrative() : demoNarrative();
}

/** Chapter in effect for a month (chapters sorted by `from`; last one whose from ≤ month). */
export function chapterForMonth(narrative: DemoNarrative, month: DemoMonth): DemoChapter {
  const sorted = [...narrative.chapters].sort((a, b) => a.from.localeCompare(b.from));
  let current = sorted[0];
  if (!current) throw new Error("demo narrative needs at least one chapter");
  for (const ch of sorted) {
    if (ch.from <= month) current = ch;
  }
  return current;
}

/** Deterministic mulberry32 PRNG — same narrative seed ⇒ identical DB. */
export function demoRng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
